---
#
# Ansible managed
#
repository:
  description: The purpose of this role is to release a fixed set of packages to machines.
  homepage: https://robertdebock.nl/
  topics: ansible, server, system, installer, ansible, molecule, tox, playbook, hacktoberfest
