---
# vars file for reboot
_reboot_requirements:
  default: []
  CentOS: yum-utils
  Fedora: dnf-utils

reboot_requirements: "{{ _reboot_requirements[ansible_distribution] | default(_reboot_requirements['default']) }}"

_reboot_needs_restarting_command:
  CentOS: needs-restarting -r
  Fedora: needs-restarting

reboot_needs_restarting_command: "{{ _reboot_needs_restarting_command[ansible_distribution] }}"

_reboot_command:
  default: shutdown -r now {{ reboot_message }}
  Alpine: reboot

reboot_command: "{{ _reboot_command[ansible_distribution] | default(_reboot_command['default']) }}"
