---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: release-centos
    box: centos/7
provisioner:
  name: ansible
  inventory:
    host_vars:
      release-fedora:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: vagrant
