---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: server-centos-6
    box: centos/6
  - name: server-centos-7
    box: centos/7
  - name: server-debian-jessie64
    box: debian/jessie64
  - name: server-debian-buster64
    box: desc/buster64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: vagrant
