---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: release-centos-6
    box: centos/6
  - name: release-centos-7
    box: centos/7
  - name: release-debian-8
    box: debian/jessie64
  - name: release-debian-9
    box: debian/stretch64
provisioner:
  name: ansible
scenario:
  name: vagrant
