---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: bootstrap-centos-6
    box: centos/6
  - name: bootstrap-centos-7
    box: centos/7
  - name: bootstrap-debian-jessie64
    box: debian/jessie64
  - name: bootstrap-debian-buster64
    box: desc/buster64
  - name: bootstrap-fedora-26-cloud-base
    box: fedora/26-cloud-base
  - name: bootstrap-fedora-27-cloud-base
    box: fedora/27-cloud-base
  - name: bootstrap-opensuse-openSUSE-42-2-x86-64
    box: opensuse/openSUSE-42.2-x86_64
  - name: bootstrap-ubuntu-trusty
    box: ubuntu/trusty64
  - name: bootstrap-ubuntu-zesty
    box: ubuntu/zesty64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: vagrant
verifier:
  name: goss
  lint:
    name: 'None'
