---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: release-centos-6
    box: centos/6
  - name: release-centos-7
    box: centos/7
  - name: release-debian-8
    box: debian/jessie64
  - name: release-debian-9
    box: debian/stretch64
  - name: release-fedora-26-cloud-base
    box: fedora/26-cloud-base
  - name: release-fedora-27-cloud-base
    box: fedora/27-cloud-base
  - name: release-opensuse-openSUSE-42-2-x86-64
    box: opensuse/openSUSE-42.2-x86_64
  - name: release-opensuse-openSUSE-42-3-x86-64
    box: opensuse/openSUSE-42.3-x86_64
  - name: release-ubuntu-trusty
    box: ubuntu/trusty64
  - name: release-ubuntu-zesty
    box: ubuntu/zesty64

provisioner:
  name: ansible
scenario:
  name: vagrant
