---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: release-centos-latest
    image: centos:latest
  - name: release-debian-latest
    image: debian:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - ANSIBLE0016

scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
