---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: release-centos-latest
    image: centos:latest
  - name: release-debian-latest
    image: debian:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      release-fedora-latest:
        ansible_python_interpreter: /usr/bin/python3
      release-fedora-rawhide:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
