---
- hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.update

  tasks:
    - name: set timezone
      timezone:
        name: Europe/Amsterdam

    - name: register packages (yum or dnf)
      shell: >
        rpm -qa --queryformat '%{NAME} %{VERSION}\n' | sort | grep -v gpg-pubkey | awk 'BEGIN { print "---\nrelease_packages:" } { print "  - "$1"-"$2 }'
      register: rpmpackages
      when:
        - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"
      notify:
        - write rpm packages to file

  handlers:
    - name: write rpm packages to file
      copy:
        content: "{{ rpmpackages.stdout }}\n"
        dest: "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      delegate_to: localhost
