Vagrant.configure("2") do |config|
  config.vm.define "reference-centos-7" do |config|
    config.vm.box = "centos/7"
    config.vm.synced_folder '.', '/vagrant', disabled: true
  end
  config.vm.define "reference-centos-8" do |config|
    config.vm.box = "centos/8"
    config.vm.synced_folder '.', '/vagrant', disabled: true
  end
end
