Vagrant.configure("2") do |config|

  config.vm.define "reference-centos-6" do |config|
    config.vm.box = "centos/6"
  end

  config.vm.define "reference-centos-7" do |config|
    config.vm.box = "centos/7"
  end

  config.vm.define("reference-debian-8") do |config|
    config.vm.box = "debian/jessie64"
  end

  config.vm.define("reference-debian-9") do |config|
    config.vm.box = "debian/stretch64"
  end

end
